In [1]:
import numpy as np

### Gunjan is working on a swap of drones that can perform light shows.
### For that, she is maintaining a list of the height of each drone and is updating that for each step.
    Height = [h1,h2,h3………hn] # height of each drone
    Delta_h = [d1,d2,d3……dn] # change in height of each drone

#### For each second she updates the Height array by adding the corresponding change to the height.

### For that, she tried out 2 methods as listed below. Help her in arranging them in ascending order of time.


    (A) Numpy operator

    import numpy as np

    def update_height(height,delta):

       height = np.array(height)

       delta = np.array(delta)

       new_height = height+delta 

       return new_height

    (B) Python operation


    def update_height(height, delta):

        new_height=[]

        for i in range(len(height)):

            new_height.append(height[i]+delta[i])

        return new_height

In [2]:
H = list(range(50,50000000))

In [3]:
dH = [5 for x in range(50,50000000)]

In [4]:
def update_height(height,delta):
    height = np.array(height)
    delta = np.array(delta)
    new_height = height + delta
    return new_height

In [5]:
%time
update_height(H,dH)

Wall time: 0 ns


array([      55,       56,       57, ..., 50000002, 50000003, 50000004])

In [6]:
def update_height_py(height, delta):
    new_height=[]
    for i in range(len(height)):
        new_height.append(height[i]+delta[i])
        
    return new_height


### Which option is right about the output of the following code snippet?

    x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10])
    x[(x >= -5) & (x <= 15)] *= -1 
    Note: Recall the masking with assignment question discussed in class

In [7]:
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10])

In [8]:
x[(x >= -5) & (x <= 15)] *= -1 

In [9]:
x

array([  5,  -9,  20,  25,   3,  -5,  16, -10])

### a. What is the last element of the output?

In [10]:
print(np.sort(np.array(['Ram','Astha','Raghavendra'])))

['Astha' 'Raghavendra' 'Ram']


In [11]:
arr1 = np.array(['Ram','Astha','Brahat'])
arr2 = np.array(['Shyam','Kalyan','Naveen'])
arr1 > arr2

array([False, False, False])

### You are given NumPy arrays A, B, and C, where:

    A.shape = (m,)

    B.shape = (n, 1)

    C.shape = (n, m)

#### Which of the following operations can be performed on A, B, and C?
##### Note: np is the alias for NumPy in the options.

In [13]:
A = np.array([1,2,3])
A.shape

(3,)

In [17]:
B = np.array([[1],[2],[3],[4]])
B.shape

(4, 1)

In [19]:
C = np.array([[1,2,4],
             [7,8,9],
             [9,5,1],
              [7,5,3]])
C.shape

(4, 3)

In [20]:
B

array([[1],
       [2],
       [3],
       [4]])

In [21]:
A

array([1, 2, 3])

In [22]:
C

array([[1, 2, 4],
       [7, 8, 9],
       [9, 5, 1],
       [7, 5, 3]])

In [28]:
C.T

array([[1, 7, 9, 7],
       [2, 8, 5, 5],
       [4, 9, 1, 3]])

In [29]:
A.reshape(3,1)

array([[1],
       [2],
       [3]])

In [31]:
np.concatenate((C.T,A.reshape(3,1)),axis = 1)

array([[1, 7, 9, 7, 1],
       [2, 8, 5, 5, 2],
       [4, 9, 1, 3, 3]])

#### Given the 2-D array X,


    X = np.arange(12).reshape(3,4)
    So, X is

    [[ 0 1 2 3] 
     [ 4 5 6 7]
     [ 8 9 10 11]]
    Which of the following is/are true statements.

In [33]:

X = np.arange(12).reshape(3,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
X.max(axis=1)

array([ 3,  7, 11])

In [37]:
X.T.max(axis=0)

array([ 3,  7, 11])

In [38]:
[i.min() for i in X]

[0, 4, 8]

### For the arrays a and b:

    import numpy as np
    a = np.zeros(27).reshape(3, 3, 3)
    b = np.arange(9).reshape(3, 3) 
    Which option will give the same output as a+b?

    Note: np.newaxis is used to create a new axis in the mentioned dimension.

In [40]:
a = np.zeros(27).reshape(3, 3, 3)
b = np.arange(9).reshape(3, 3) 

In [43]:
a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [44]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
b[np.newaxis,:,:]+a

array([[[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]],

       [[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]],

       [[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]])

### Given the NumPy array arr, which of the following line of code will return the expected output?

    import numpy as np
    arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])

    a.

    arr1 = np.array([[2,2,2,2]])
    def func(x, y):
        return x * y
    vec = np.vectorize(func)
    vec(arr,arr1)

    b.

    arr1 = np.array([[2],[2],[2],[2]])
    def func(x, y):
        return x * y
    vec = np.vectorize(func)
    vec(arr, arr1)


    c.

    arr1 = 2
    def func(x, y):
        return x * y
    vec = np.vectorize(func)
    vec(arr, arr1)

    Expected output:

    array ([[4,6,8,10],
            [2,14,6,10],
            [4,16,12,18],
            [22,46,24,38]])

In [48]:
arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])

In [49]:
arr1 = np.array([[2,2,2,2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr,arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [50]:
arr1 = np.array([[2],[2],[2],[2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [51]:
arr1 = 2
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

### Which of the following option(s) can add 1 to each element of array A?

    A = np.array([2, 0, 1, 9, 1, 1, 1, 0, 3, 5])

In [52]:
A = np.array([2, 0, 1, 9, 1, 1, 1, 0, 3, 5])

In [53]:
A+1

array([ 3,  1,  2, 10,  2,  2,  2,  1,  4,  6])

In [54]:
[x+1 for x in A]

[3, 1, 2, 10, 2, 2, 2, 1, 4, 6]

In [56]:
list(map(lambda x:x+1,A))

[3, 1, 2, 10, 2, 2, 2, 1, 4, 6]

### What will be the outcome of the following code snippet ?

    x = np.ones((5,5))
    x[1:-1,1:-1] = 0

In [58]:
x = np.ones((5,5))


In [61]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [62]:
x[1:-1,1:-1] = 0

In [63]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Given a Numpy array of integers as an input to the function binary(), complete the given function to convert each element in the array into its binary representation.

    For example: In binary, 5 => 101, 7 => 111, 10 => 1010.

    Note: You are not allowed to use the inbuilt bin() function and both input and output array have elements of datatype 'int'.

    Input Format:

    A list is taken as input which is then typecasted to a NumPy array.
    Output Format:

    A NumPy array is printed.
    Sample Input:

    [[2,3,4], [5,6,7]]
    Sample Output:

    [[ 10  11 100]
     [101 110 111]]  

In [64]:
def binary(arr):
    def con_bin(n):
        s = ""
        while n>0:
            s = s+str(n%2)
            n = n//2
        return int(s[::-1])
    return np.vectorize(con_bin)(arr)

In [65]:
binary([[2,3,4],
        [5,6,7]])

array([[ 10,  11, 100],
       [101, 110, 111]])

### You are a Teaching Assistant of the DSML course. You have access to every student’s marks in every quiz. The marks are stored in a matrix where matrix[i][j] represents the marks of the ith student in the jth quiz.

    The course instructor wants you to sort the marks of students according to jth quiz in increasing order so that he can evaluate the performance of students in that particular quiz.

    Here, you have to create a python program using which the instructor can sort the data on the basis of a given column(quiz). The program will return the matrix with the marks sorted in jth quiz.

    The dimension of the input matrix is mxn, the output is expected to be a 2d numpy matrix of dimension mxn, but in the output the jth column must be arranged in the ascending order.

    Note: The input will be 2D list not array. First convert it to array.

    Input Format:

    Number of test cases
    For each test case, number of rows for matrix and the column to be sorted in a new line.
    For each row in matrix, space separated integers are taken as input in a new line.
    Output Format:

    The 2D matrix, or each row in matrix space separated integers
    Sample Input:

    1
    3 2 
    5 3 9
    2 1 4
    7 6 8
    Sample Output:

    [[2 1 4]
     [5 3 9]
     [7 6 8]]

In [68]:
A = np.array([[5, 3, 9],
            [2 ,1, 4],
            [7 ,6 ,8]])

In [69]:
A

array([[5, 3, 9],
       [2, 1, 4],
       [7, 6, 8]])

In [73]:
j = 2

In [74]:
A[:,1]

array([3, 1, 6])

In [75]:
A[:,j-1]

array([3, 1, 6])

In [76]:
A[:,j-1].argsort()

array([1, 0, 2], dtype=int64)

In [77]:
A[A[:,j-1].argsort()]

array([[2, 1, 4],
       [5, 3, 9],
       [7, 6, 8]])

### You are a developer for Scalar, and are tasked to write a program that can find the number of times a student has accessed a particular question.

    For this, you proposed that every time a student opens a question, the question’s id will be appended to the row representing the student’s id in a matrix. For example, if student i opens question j, j will be appended to ith row of the matrix.
    For the prototype, we have limited the number of questions to 10 for consideration. So id of questions <=10. Return the matrix with the same number of rows(m) as that of the input matrix, but this time matrix[i][j] should represent the number of times student i accessed question j. The output matrix is a 2d-numpy matrix of dimension (m*10).

    Input Format:

    number of test cases
    for each test case (number of rows for matrix, number of columns for the matrix)
    for each row in matrix space separated integers
    Output Format:

    Return the 2d numpy array.
    Sample input:

    1
    5
    1 1 2 5 7 6 7 7 6 3 
    8 5 4 7 5 2 6 10 1 7 
    4 3 10 4 4 4 3 1 4 3 
    1 4 1 1 8 4 9 8 5 5 
    1 1 4 4 2 10 5 6 8 1 

    Sample output:

    [[2 1 1 0 1 2 3 0 0 0]
     [1 1 0 1 2 1 2 1 0 1]
     [1 0 3 5 0 0 0 0 0 1]
     [3 0 0 2 2 0 0 2 1 0]
     [3 1 0 2 1 1 0 1 0 1]]

In [79]:
arr = np.array([[1, 1, 2, 5, 7, 6, 7, 7, 6, 3], 
[8, 5, 4 ,7 ,5 ,2 ,6 ,10, 1, 7], 
[4, 3, 10, 4, 4, 4, 3, 1, 4, 3], 
[1, 4, 1, 1, 8, 4, 9, 8, 5, 5], 
[1, 1, 4, 4, 2, 10, 5, 6, 8, 1]])

In [80]:
arr

array([[ 1,  1,  2,  5,  7,  6,  7,  7,  6,  3],
       [ 8,  5,  4,  7,  5,  2,  6, 10,  1,  7],
       [ 4,  3, 10,  4,  4,  4,  3,  1,  4,  3],
       [ 1,  4,  1,  1,  8,  4,  9,  8,  5,  5],
       [ 1,  1,  4,  4,  2, 10,  5,  6,  8,  1]])

In [85]:
r = arr[0]

In [92]:
unique,freq = np.unique(r,return_counts = True)
unique,freq

(array([1, 2, 3, 5, 6, 7]), array([2, 1, 1, 1, 2, 3], dtype=int64))

In [91]:
zeros = np.zeros(len(r),dtype="int")
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [95]:
zeros[unique-1] = freq

In [96]:
zeros

array([2, 1, 1, 0, 1, 2, 3, 0, 0, 0])

In [97]:
def countfreq(arr2d):
    
    def asdasd(row):
        row  = np.array(row)
        uniq, freq = np.unique(row,return_counts=True)
        zeros = np.zeros(len(row),dtype="int")
        zeros[uniq-1] = freq
        return zeros
    
    ans = []

    for i in arr2d:
        ans.append(asdasd(i))
    return np.array(ans)

In [98]:
countfreq(arr)

array([[2, 1, 1, 0, 1, 2, 3, 0, 0, 0],
       [1, 1, 0, 1, 2, 1, 2, 1, 0, 1],
       [1, 0, 3, 5, 0, 0, 0, 0, 0, 1],
       [3, 0, 0, 2, 2, 0, 0, 2, 1, 0],
       [3, 1, 0, 2, 1, 1, 0, 1, 0, 1]])