In [1]:
import numpy as np

In [2]:
A = [1,2,3,4,5,6]

In [3]:
[i**2 for i in A]

[1, 4, 9, 16, 25, 36]

In [5]:
A = np.array(A)

In [6]:
A


array([1, 2, 3, 4, 5, 6])

In [7]:
A**2

array([ 1,  4,  9, 16, 25, 36], dtype=int32)

In [17]:
A = np.array(range(1,101,1))

In [18]:
A

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [19]:
A.ndim

1

In [20]:
A.shape

(100,)

In [23]:
A.reshape((25,4))

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20],
       [ 21,  22,  23,  24],
       [ 25,  26,  27,  28],
       [ 29,  30,  31,  32],
       [ 33,  34,  35,  36],
       [ 37,  38,  39,  40],
       [ 41,  42,  43,  44],
       [ 45,  46,  47,  48],
       [ 49,  50,  51,  52],
       [ 53,  54,  55,  56],
       [ 57,  58,  59,  60],
       [ 61,  62,  63,  64],
       [ 65,  66,  67,  68],
       [ 69,  70,  71,  72],
       [ 73,  74,  75,  76],
       [ 77,  78,  79,  80],
       [ 81,  82,  83,  84],
       [ 85,  86,  87,  88],
       [ 89,  90,  91,  92],
       [ 93,  94,  95,  96],
       [ 97,  98,  99, 100]])

In [24]:
A = np.array([1,2,3,4,5,6,7,8,])

In [25]:
A

array([1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
A.ndim,A.shape

(1, (8,))

In [30]:
np.arange(1,10.5,0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [31]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [38]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [49]:
A = np.array([1,2,"A"])
A.dtype

dtype('<U11')

In [41]:
A

array(['1', '2', 'A'], dtype='<U11')

In [42]:
A[1] = 5

In [44]:
A[-1] = "SUNNY"

In [45]:
A

array(['1', '5', 'SUNNY'], dtype='<U11')

In [47]:
A = np.array([1,2,3.0])
A

array([1., 2., 3.])

In [48]:
A.dtype

dtype('float64')

In [57]:
A = np.array([1,2,3])
A.dtype

dtype('int32')

In [61]:
A**3000

array([         1,          0, 2132598113], dtype=int32)

In [67]:
A = np.arange(1,25).reshape(6,4)


In [68]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [69]:
A.shape

(6, 4)

In [78]:
a = np.array([1, 2, 3,4,5], ndmin = 2)
a

array([[1, 2, 3, 4, 5]])

In [79]:
a.shape

(1, 5)

In [80]:
a.ndim

2

In [85]:
np.arange(1,13).shape

(12,)

In [83]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [86]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [95]:
a.resize(1,12)

In [96]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [98]:
A = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [99]:
np.resize(A,(3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [101]:
np.resize(A,(3,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12,  1,  2,  3]])

In [107]:
np.resize(A,(12,12))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [115]:
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [116]:
a.resize((6,2),refcheck = False)

In [117]:
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 0],
       [0, 0],
       [0, 0]])

In [123]:

a = np.array([1,2,3,4,5,6,7])
a
np.resize(a,(5,9))

array([[1, 2, 3, 4, 5, 6, 7, 1, 2],
       [3, 4, 5, 6, 7, 1, 2, 3, 4],
       [5, 6, 7, 1, 2, 3, 4, 5, 6],
       [7, 1, 2, 3, 4, 5, 6, 7, 1],
       [2, 3, 4, 5, 6, 7, 1, 2, 3]])

In [122]:
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 0],
       [0, 0],
       [0, 0]])

In [124]:
c = a

In [127]:
  a.resize((3,4),refcheck ) 

In [128]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 0],
       [0, 0, 0, 0]])

In [135]:
a = np.arange(3).reshape(1,3)

In [136]:
a

array([[0, 1, 2]])

In [137]:
a.T

array([[0],
       [1],
       [2]])

In [134]:
a = np.arange(3).T
a

array([0, 1, 2])

In [140]:
a.flatten()

array([0, 1, 2])

In [142]:

a = np.array([1,2,3,4,5,6,7])
a
a = np.resize(a,(5,9))
a

array([[1, 2, 3, 4, 5, 6, 7, 1, 2],
       [3, 4, 5, 6, 7, 1, 2, 3, 4],
       [5, 6, 7, 1, 2, 3, 4, 5, 6],
       [7, 1, 2, 3, 4, 5, 6, 7, 1],
       [2, 3, 4, 5, 6, 7, 1, 2, 3]])

In [143]:
a

array([[1, 2, 3, 4, 5, 6, 7, 1, 2],
       [3, 4, 5, 6, 7, 1, 2, 3, 4],
       [5, 6, 7, 1, 2, 3, 4, 5, 6],
       [7, 1, 2, 3, 4, 5, 6, 7, 1],
       [2, 3, 4, 5, 6, 7, 1, 2, 3]])

In [144]:
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1,
       2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2,
       3])

In [145]:
a

array([[1, 2, 3, 4, 5, 6, 7, 1, 2],
       [3, 4, 5, 6, 7, 1, 2, 3, 4],
       [5, 6, 7, 1, 2, 3, 4, 5, 6],
       [7, 1, 2, 3, 4, 5, 6, 7, 1],
       [2, 3, 4, 5, 6, 7, 1, 2, 3]])

In [152]:
A= np.resize(a,(5,10))
A

array([[1, 2, 3, 4, 5, 6, 7, 1, 2, 3],
       [4, 5, 6, 7, 1, 2, 3, 4, 5, 6],
       [7, 1, 2, 3, 4, 5, 6, 7, 1, 2],
       [3, 4, 5, 6, 7, 1, 2, 3, 4, 5],
       [6, 7, 1, 2, 3, 1, 2, 3, 4, 5]])

In [154]:
A.reshape(25,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [1, 2],
       [3, 4],
       [5, 6],
       [7, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [1, 2],
       [3, 4],
       [5, 6],
       [7, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [1, 2],
       [3, 1],
       [2, 3],
       [4, 5]])

In [156]:
A.size

50

In [157]:
A

array([[1, 2, 3, 4, 5, 6, 7, 1, 2, 3],
       [4, 5, 6, 7, 1, 2, 3, 4, 5, 6],
       [7, 1, 2, 3, 4, 5, 6, 7, 1, 2],
       [3, 4, 5, 6, 7, 1, 2, 3, 4, 5],
       [6, 7, 1, 2, 3, 1, 2, 3, 4, 5]])

In [158]:
A.reshape(-1,5)

array([[1, 2, 3, 4, 5],
       [6, 7, 1, 2, 3],
       [4, 5, 6, 7, 1],
       [2, 3, 4, 5, 6],
       [7, 1, 2, 3, 4],
       [5, 6, 7, 1, 2],
       [3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5],
       [6, 7, 1, 2, 3],
       [1, 2, 3, 4, 5]])

In [159]:
A.reshape(5,-1)

array([[1, 2, 3, 4, 5, 6, 7, 1, 2, 3],
       [4, 5, 6, 7, 1, 2, 3, 4, 5, 6],
       [7, 1, 2, 3, 4, 5, 6, 7, 1, 2],
       [3, 4, 5, 6, 7, 1, 2, 3, 4, 5],
       [6, 7, 1, 2, 3, 1, 2, 3, 4, 5]])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [161]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [164]:
np.identity(n=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [165]:
np.diag([1,2,3,4,5,6])

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [167]:
np.diag(np.diag([1,2,3]))

array([1, 2, 3])

In [169]:
M

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [172]:
M[11]

11

In [174]:
M = np.arange(12)
M  = M.reshape(3,4)
M

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [176]:
M[1,2]

6

In [177]:
M[[1,2],[-1,-1]]

array([ 7, 11])

In [181]:
M[[2,2,1,2]]

array([[ 8,  9, 10, 11],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [182]:
M[[0,0,1],[0,1,2]]

array([0, 1, 6])

In [183]:
M

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [188]:
M[1:2]

array([[4, 5, 6, 7]])

In [191]:
M[0:,2]

array([ 2,  6, 10])

In [193]:
M[:,2:]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [197]:
M[:-1,:-1]

array([[0, 1, 2],
       [4, 5, 6]])

In [198]:
M = np.arange(12)
M  = M.reshape(3,4)
M

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [199]:
M<6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [200]:
M[M<6]

array([0, 1, 2, 3, 4, 5])

In [210]:
M = np.random.randint(0,50,(4,8))

In [211]:
M

array([[42,  8, 18, 34, 30, 30, 17, 30],
       [11, 49, 22, 23, 41, 28,  6, 23],
       [35, 10, 25, 45,  7, 36, 34, 20],
       [38, 21, 34, 41, 38, 22, 40, 10]])

In [213]:
M[M<20]

array([ 8, 18, 17, 11,  6, 10,  7, 10])

In [218]:
M[(M%2==0) | (M%5==0)] = -1

In [219]:
M

array([[-1, -1, -1, -1, -1, -1, 17, -1],
       [11, 49, -1, 23, 41, -1, -1, 23],
       [-1, -1, -1, -1,  7, -1, -1, -1],
       [-1, 21, -1, 41, -1, -1, -1, -1]])

In [220]:
M

array([[-1, -1, -1, -1, -1, -1, 17, -1],
       [11, 49, -1, 23, 41, -1, -1, 23],
       [-1, -1, -1, -1,  7, -1, -1, -1],
       [-1, 21, -1, 41, -1, -1, -1, -1]])

In [228]:
M.reshape(8,-1)

array([[-1, -1, -1, -1],
       [-1, -1, 17, -1],
       [11, 49, -1, 23],
       [41, -1, -1, 23],
       [-1, -1, -1, -1],
       [ 7, -1, -1, -1],
       [-1, 21, -1, 41],
       [-1, -1, -1, -1]])

In [232]:
M.resize((5,5),refcheck = False)

In [237]:
np.ceil(np.linalg.inv(M))

array([[ 1.00000000e+00,  0.00000000e+00, -0.00000000e+00,
         1.00000000e+00, -0.00000000e+00],
       [ 1.18316790e+16,  1.00000000e+00,  1.00000000e+00,
         5.91583951e+15, -1.77475185e+16],
       [-6.76095944e+15, -0.00000000e+00, -0.00000000e+00,
        -3.38047972e+15,  1.01414392e+16],
       [-1.06751991e+15, -0.00000000e+00, -0.00000000e+00,
        -5.33759956e+14,  1.60127987e+15],
       [-4.00319967e+15,  1.00000000e+00, -0.00000000e+00,
        -2.00159983e+15,  6.00479950e+15]])

In [238]:
M

array([[-1, -1, -1, -1, -1],
       [-1, 17, -1, 11, 49],
       [-1, 23, 41, -1, -1],
       [23, -1, -1, -1, -1],
       [ 7, -1, -1, -1, -1]])

In [239]:
M = np.random.randint(0,50,(4,8))

In [240]:
M

array([[ 4, 22, 44, 27, 20, 48, 40, 28],
       [29,  1, 17, 14, 21, 38, 30, 38],
       [37, 24, 28, 43, 44,  7,  1, 46],
       [45, 19, 42, 17, 43, 49,  2, 23]])

In [241]:
M.sum()

891

In [242]:
M.sum(axis = 0)

array([115,  66, 131, 101, 128, 142,  73, 135])

In [243]:
M.sum(axis = 1)

array([233, 188, 230, 240])

In [244]:
M = np.random.randint(0,50,(4,8,2))

In [252]:
41+37

78

In [245]:
M

array([[[41, 37],
        [48,  7],
        [45, 42],
        [ 4,  2],
        [41,  3],
        [10, 14],
        [14, 43],
        [22, 41]],

       [[ 5, 22],
        [14, 33],
        [26, 42],
        [20, 23],
        [26,  5],
        [31, 33],
        [48, 38],
        [33,  7]],

       [[ 4, 43],
        [23, 46],
        [18, 48],
        [36, 44],
        [ 7, 38],
        [17, 31],
        [17, 49],
        [11, 15]],

       [[42, 31],
        [36,  3],
        [38, 14],
        [ 9, 34],
        [ 8, 48],
        [32, 41],
        [29,  0],
        [37,  8]]])

In [246]:
M.sum()

1677

In [250]:
M.sum(axis = 2)

array([[78, 55, 87,  6, 44, 24, 57, 63],
       [27, 47, 68, 43, 31, 64, 86, 40],
       [47, 69, 66, 80, 45, 48, 66, 26],
       [73, 39, 52, 43, 56, 73, 29, 45]])

In [262]:
M = np.random.randint(0,50,(4,8))

In [263]:
M

array([[45,  8, 14, 40,  1, 16,  3, 19],
       [38, 38, 33,  8, 11, 35,  3,  3],
       [ 0, 43, 45, 43,  3, 46, 27,  0],
       [36,  8, 36, 43,  3, 20, 16, 17]])

In [264]:
np.mean(M,axis =0 )

array([29.75, 24.25, 32.  , 33.5 ,  4.5 , 29.25, 12.25,  9.75])

In [265]:
np.min(M,axis = 0)

array([ 0,  8, 14,  8,  1, 16,  3,  0])

In [275]:
M

array([[45,  8, 14, 40,  1, 16,  3, 19],
       [38, 38, 33,  8, 11, 35,  3,  3],
       [ 0, 43, 45, 43,  3, 46, 27,  0],
       [36,  8, 36, 43,  3, 20, 16, 17]])

In [267]:
np.all(M,axis = 0)

array([False,  True,  True,  True,  True,  True,  True, False])

In [268]:
np.all(M,axis = 1)

array([ True,  True, False,  True])

In [277]:
np.all(M,axis = 0,where=(0))

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [284]:
np.where(M%2==0,1,0)

array([[0, 1, 1, 1, 0, 1, 0, 0],
       [1, 1, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 1, 0, 1],
       [1, 1, 1, 0, 0, 1, 1, 0]])

In [285]:
M = np.random.randint(0,50,(4,8))
N = np.random.randint(0,50,(4,8))

In [286]:
M,N

(array([[43,  4, 26, 26,  0, 49, 48,  9],
        [30, 12, 21,  5, 43, 34, 41, 15],
        [22, 42, 32, 41, 25, 37, 26, 13],
        [26, 16,  8, 26, 44,  6, 21,  5]]),
 array([[38, 23, 42, 10, 23,  2, 13, 17],
        [26, 33, 29, 39, 40, 18, 30, 35],
        [26, 27,  9, 44,  6, 31, 23, 45],
        [ 8,  1, 10, 31, 49,  2, 20, 49]]))

In [292]:
(M<N)

array([[False,  True,  True, False,  True, False, False,  True],
       [False,  True,  True,  True, False, False, False,  True],
       [ True, False, False,  True, False, False, False,  True],
       [False, False,  True,  True,  True, False, False,  True]])

In [291]:
np.any(M<N,axis= 0)

array([ True,  True,  True,  True,  True, False, False,  True])

In [293]:
np.all(M<N,axis= 0)

array([False, False, False, False, False, False, False,  True])

In [294]:
M

array([[43,  4, 26, 26,  0, 49, 48,  9],
       [30, 12, 21,  5, 43, 34, 41, 15],
       [22, 42, 32, 41, 25, 37, 26, 13],
       [26, 16,  8, 26, 44,  6, 21,  5]])

In [295]:
np.sort(M)

array([[ 0,  4,  9, 26, 26, 43, 48, 49],
       [ 5, 12, 15, 21, 30, 34, 41, 43],
       [13, 22, 25, 26, 32, 37, 41, 42],
       [ 5,  6,  8, 16, 21, 26, 26, 44]])

In [297]:
M

array([[43,  4, 26, 26,  0, 49, 48,  9],
       [30, 12, 21,  5, 43, 34, 41, 15],
       [22, 42, 32, 41, 25, 37, 26, 13],
       [26, 16,  8, 26, 44,  6, 21,  5]])

In [298]:
np.sort(M,axis= 1)

array([[ 0,  4,  9, 26, 26, 43, 48, 49],
       [ 5, 12, 15, 21, 30, 34, 41, 43],
       [13, 22, 25, 26, 32, 37, 41, 42],
       [ 5,  6,  8, 16, 21, 26, 26, 44]])

In [296]:
np.sort(M,axis= 0)

array([[22,  4,  8,  5,  0,  6, 21,  5],
       [26, 12, 21, 26, 25, 34, 26,  9],
       [30, 16, 26, 26, 43, 37, 41, 13],
       [43, 42, 32, 41, 44, 49, 48, 15]])

In [302]:
np.argmin(M,axis = 0)+1

array([3, 1, 4, 2, 1, 4, 4, 4], dtype=int64)

In [301]:
M

array([[43,  4, 26, 26,  0, 49, 48,  9],
       [30, 12, 21,  5, 43, 34, 41, 15],
       [22, 42, 32, 41, 25, 37, 26, 13],
       [26, 16,  8, 26, 44,  6, 21,  5]])

In [303]:
M

array([[43,  4, 26, 26,  0, 49, 48,  9],
       [30, 12, 21,  5, 43, 34, 41, 15],
       [22, 42, 32, 41, 25, 37, 26, 13],
       [26, 16,  8, 26, 44,  6, 21,  5]])

In [304]:
np.argsort(M,axis = 0)

array([[2, 0, 3, 1, 0, 3, 3, 3],
       [3, 1, 1, 0, 2, 1, 2, 0],
       [1, 3, 0, 3, 1, 2, 1, 2],
       [0, 2, 2, 2, 3, 0, 0, 1]], dtype=int64)

In [306]:
!gdown 1kXqcJo4YzmwF1G2BPoA17CI49TZVHANF

Downloading...
From: https://drive.google.com/uc?id=1kXqcJo4YzmwF1G2BPoA17CI49TZVHANF
To: C:\Users\sunny\Data Science Studies\GitHub_Desktop\Data-Science-Numpy-Pandas\fitness.txt

  0%|          | 0.00/3.14k [00:00<?, ?B/s]
100%|##########| 3.14k/3.14k [00:00<00:00, 2.64MB/s]


In [310]:
data = np.loadtxt("fitness.txt",dtype="str")

In [311]:
data

array([['06-10-2017', '5464', '200', '181', '5', '0', '66'],
       ['07-10-2017', '6041', '100', '197', '8', '0', '66'],
       ['08-10-2017', '25', '100', '0', '5', '0', '66'],
       ['09-10-2017', '5461', '100', '174', '4', '0', '66'],
       ['10-10-2017', '6915', '200', '223', '5', '500', '66'],
       ['11-10-2017', '4545', '100', '149', '6', '0', '66'],
       ['12-10-2017', '4340', '100', '140', '6', '0', '66'],
       ['13-10-2017', '1230', '100', '38', '7', '0', '66'],
       ['14-10-2017', '61', '100', '1', '5', '0', '66'],
       ['15-10-2017', '1258', '100', '40', '6', '0', '65'],
       ['16-10-2017', '3148', '100', '101', '8', '0', '65'],
       ['17-10-2017', '4687', '100', '152', '5', '0', '65'],
       ['18-10-2017', '4732', '300', '150', '6', '500', '65'],
       ['19-10-2017', '3519', '100', '113', '7', '0', '65'],
       ['20-10-2017', '1580', '100', '49', '5', '0', '65'],
       ['21-10-2017', '2822', '100', '86', '6', '0', '65'],
       ['22-10-2017', '181', '10

In [312]:
data.shape

(96, 7)

In [323]:
data.T[0]

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [324]:
date,step_count,mood,calories,sleepHours, activityStatus,weight = data.T

In [330]:
step_count = step_count.astype("int")

In [334]:
calories = calories.astype("int")

In [336]:
sleepHours = sleepHours.astype("int")

In [339]:
weight = weight.astype("int")

In [340]:
mood

array(['200', '100', '100', '100', '200', '100', '100', '100', '100',
       '100', '100', '100', '300', '100', '100', '100', '100', '200',
       '200', '200', '200', '200', '200', '300', '200', '300', '300',
       '300', '300', '300', '300', '300', '200', '300', '300', '300',
       '300', '300', '300', '300', '300', '300', '300', '200', '300',
       '300', '300', '300', '300', '300', '300', '300', '300', '200',
       '100', '300', '300', '300', '300', '300', '300', '300', '100',
       '200', '200', '100', '100', '200', '200', '300', '200', '200',
       '100', '200', '100', '200', '200', '100', '100', '100', '100',
       '300', '200', '300', '200', '100', '100', '100', '200', '200',
       '100', '100', '300', '200', '200', '300'], dtype='<U10')

In [341]:
np.unique(mood)

array(['100', '200', '300'], dtype='<U10')

In [346]:
mood[mood == "300"] = "Happy"

In [348]:
mood[mood == "200"] = "Neutral"
mood[mood == "100"] = "Sad"


In [349]:
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [352]:
activityStatus[activityStatus == "0"] = "InActive"
activityStatus[activityStatus == "500"] = "Active"

In [353]:
activityStatus

array(['InActive', 'InActive', 'InActive', 'InActive', 'Active',
       'InActive', 'InActive', 'InActive', 'InActive', 'InActive',
       'InActive', 'InActive', 'Active', 'InActive', 'InActive',
       'InActive', 'InActive', 'InActive', 'InActive', 'InActive',
       'InActive', 'InActive', 'InActive', 'InActive', 'InActive',
       'Active', 'InActive', 'InActive', 'InActive', 'InActive', 'Active',
       'InActive', 'InActive', 'InActive', 'InActive', 'InActive',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'InActive', 'InActive', 'InActive',
       'InActive', 'InActive', 'InActive', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'InActive', 'Active', 'Active',
       'InActive', 'Active', 'Active', 'Active', 'Active', 'Active',
       'InActive', 'Active', 'Active', 'Active', 'Active', 'InActive',
       'InActive', 'InActive', 'InActi

In [354]:
np.mean(step_count)

2935.9375

In [356]:
date[np.argmax(step_count)]

'14-12-2017'

In [360]:
np.unique(mood,return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([40, 27, 29], dtype=int64))

In [365]:
step_count[mood == "Happy"].mean(),step_count[mood == "Sad"].mean(),step_count[mood == "Neutral"].mean()

(3392.725, 2103.0689655172414, 3153.777777777778)

In [368]:
np.unique(mood[step_count > 4000],return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([22,  9,  7], dtype=int64))

In [370]:
np.unique(mood[step_count < 2000],return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([13,  8, 18], dtype=int64))

In [372]:
M = np.arange(12).reshape(3,4)

In [373]:
M



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [374]:
M+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [375]:
a = np.array([1,2,3])

In [376]:
a

array([1, 2, 3])

In [377]:
M

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [382]:
a.reshape(-1,3).T + M

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [383]:
A = np.arange(12).reshape(3,4)
B = np.arange(12).reshape(3,4)

In [385]:
A,B

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]))

In [386]:
A+B

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [389]:
A + B[0,:]

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

In [390]:
A*B

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [395]:
A@B.T

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

In [403]:
A,B.T

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]]))

In [396]:
np.dot(A,B.T)

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

In [397]:
np.matmul(A,B.T)

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

In [402]:
B.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [400]:
A


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [399]:
B.T@A

array([[ 80,  92, 104, 116],
       [ 92, 107, 122, 137],
       [104, 122, 140, 158],
       [116, 137, 158, 179]])

In [408]:
np.log(np.arange(1,13).reshape(3,4))

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527, 2.48490665]])

In [409]:
import math

In [414]:
nplog = np.vectorize(math.log)

In [418]:
nplog(np.arange(1,11).reshape(2,5),10)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ]])

In [423]:
np.array([0,10,20,30],ndmin=2).T + np.array([0,1,2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [426]:
np.tile(np.arange(0,40,10),(4,2))

array([[ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30]])

In [433]:
A = np.tile(np.arange(9),(10,1))

In [434]:
A

array([[0, 1, 2, 3, 4, 5, 6, 7, 8],
       [0, 1, 2, 3, 4, 5, 6, 7, 8],
       [0, 1, 2, 3, 4, 5, 6, 7, 8],
       [0, 1, 2, 3, 4, 5, 6, 7, 8],
       [0, 1, 2, 3, 4, 5, 6, 7, 8],
       [0, 1, 2, 3, 4, 5, 6, 7, 8],
       [0, 1, 2, 3, 4, 5, 6, 7, 8],
       [0, 1, 2, 3, 4, 5, 6, 7, 8],
       [0, 1, 2, 3, 4, 5, 6, 7, 8],
       [0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [454]:
np.split(A,[4,6,8],axis=0)

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8]])]

In [458]:
np.vsplit(A,5)

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8]])]

In [461]:
np.hsplit(A,3)

[array([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]),
 array([[3, 4, 5],
        [3, 4, 5],
        [3, 4, 5],
        [3, 4, 5],
        [3, 4, 5],
        [3, 4, 5],
        [3, 4, 5],
        [3, 4, 5],
        [3, 4, 5],
        [3, 4, 5]]),
 array([[6, 7, 8],
        [6, 7, 8],
        [6, 7, 8],
        [6, 7, 8],
        [6, 7, 8],
        [6, 7, 8],
        [6, 7, 8],
        [6, 7, 8],
        [6, 7, 8],
        [6, 7, 8]])]

In [468]:
A = np.array([0, 1, 2, 3, 4])
B = np.array([5, 6 ,7 ,8, 9])



In [465]:
A

array([0, 1, 2, 3, 4])

In [469]:
np.vstack((A,B))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [473]:
np.concatenate((A,B),axis = 0)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [474]:
A = np.array([0, 1, 2, 3, 4])



In [475]:
id(A)

1287497758736

In [476]:
id(A[0])

1287497623984

In [477]:
A[0] = 5

In [478]:
A

array([5, 1, 2, 3, 4])

In [479]:
id(A)

1287497758736

In [480]:
X = A

In [481]:
X

array([5, 1, 2, 3, 4])

In [482]:
id(X)

1287497758736

In [483]:
X[0] = 6

In [484]:
X

array([6, 1, 2, 3, 4])

In [485]:
id(X),id(A)

(1287497758736, 1287497758736)

In [486]:
A,X

(array([6, 1, 2, 3, 4]), array([6, 1, 2, 3, 4]))

In [487]:
M = np.copy(A)

In [489]:
id(M),id(A),id(X)

(1287486453776, 1287497758736, 1287497758736)

In [490]:
M[0] = 7

In [491]:
M

array([7, 1, 2, 3, 4])

In [492]:
A

array([6, 1, 2, 3, 4])

In [493]:
X

array([6, 1, 2, 3, 4])

In [495]:
id(M),id(X)

(1287486453776, 1287497758736)

In [496]:
a = np.array([0,1,2,3,4,5])

In [497]:

b = a[a%1 == 0]

b

array([0, 1, 2, 3, 4, 5])

In [498]:
b[0] = 10

In [499]:
b

array([10,  1,  2,  3,  4,  5])

In [500]:
a[:2]

array([0, 1])

In [503]:
X = np.arange(1,25).reshape(4,2,3)

In [504]:
X

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [514]:
X[:,:,-1]

array([[ 3,  6],
       [ 9, 12],
       [15, 18],
       [21, 24]])

In [517]:
24*5

120

In [518]:
X = np.arange(1,121).reshape(3,2,4,5)

In [519]:
X

array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]],

        [[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]]],


       [[[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]],

        [[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]]],


       [[[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]],

        [[101, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [111, 112, 113, 114, 115],
         [116, 117, 118, 119, 120]]]])

In [526]:
X[:,:,:,-1]

array([[[  5,  10,  15,  20],
        [ 25,  30,  35,  40]],

       [[ 45,  50,  55,  60],
        [ 65,  70,  75,  80]],

       [[ 85,  90,  95, 100],
        [105, 110, 115, 120]]])

In [527]:
X = np.arange(1,121).reshape(24,5)

In [528]:
X

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115],
       [116, 117, 118, 119, 120]])

In [535]:
row = np.array([0,1,5,10])
row[:,np.newaxis]

array([[ 0],
       [ 1],
       [ 5],
       [10]])

In [536]:
X[row[:,np.newaxis]]

array([[[ 1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10]],

       [[26, 27, 28, 29, 30]],

       [[51, 52, 53, 54, 55]]])

In [541]:
a = np.arange(1,5,1)

b = a
c = a.copy()
b[2] = 99
c[2] = 99
np.shares_memory(a,b),np.shares_memory(a,c)


(True, False)

In [540]:
a,b

(array([ 1,  2, 99,  4]), array([ 1,  2, 99,  4]))

In [542]:
df = pd.read_csv("gapminder-Copy1.csv")

<IPython.core.display.Javascript object>

In [543]:
df

country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [557]:
d = df.groupby(["continent"])["life_exp"].mean().reset_index()


In [558]:
d

continent   life_exp
0    Africa  48.865330
1  Americas  64.658737
2      Asia  60.064903
3    Europe  71.903686
4   Oceania  74.326208

In [559]:
df["total_GDP"] = df["gdp_cap"] * df["population"]

In [564]:
df["total_GDP"] = df["total_GDP"]/1000000000

In [565]:
df

country  year  population continent  life_exp     gdp_cap  total_GDP
0     Afghanistan  1952     8425333      Asia    28.801  779.445314   6.567086
1     Afghanistan  1957     9240934      Asia    30.332  820.853030   7.585449
2     Afghanistan  1962    10267083      Asia    31.997  853.100710   8.758856
3     Afghanistan  1967    11537966      Asia    34.020  836.197138   9.648014
4     Afghanistan  1972    13079460      Asia    36.088  739.981106   9.678553
...           ...   ...         ...       ...       ...         ...        ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306   6.508241
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786   7.422612
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960   9.037851
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623   8.015111
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298   5.782658

[1704 rows x 7 columns]

In [585]:
# df.iloc[5:50,1:5]

In [588]:
df.loc[[5,6,7]]

country  year  population continent  life_exp     gdp_cap  total_GDP
5  Afghanistan  1977    14880372      Asia    38.438  786.113360  11.697659
6  Afghanistan  1982    12881816      Asia    39.854  978.011439  12.598563
7  Afghanistan  1987    13867957      Asia    40.822  852.395945  11.820990

In [591]:
df.loc[[1,2,3,95,11,101]]

country  year  population continent  life_exp       gdp_cap  total_GDP
1    Afghanistan  1957     9240934      Asia    30.332    820.853030   7.585449
2    Afghanistan  1962    10267083      Asia    31.997    853.100710   8.758856
3    Afghanistan  1967    11537966      Asia    34.020    836.197138   9.648014
95       Bahrain  2007      708573      Asia    75.635  29796.048340  21.112675
11   Afghanistan  2007    31889923      Asia    43.828    974.580338  31.079292
101   Bangladesh  1977    80428306      Asia    46.923    659.877232  53.072808

In [602]:
df.loc[1704] = df.loc[101]

In [603]:
df

country  year  population continent  life_exp     gdp_cap  total_GDP
0     Afghanistan  1952     8425333      Asia    28.801  779.445314   6.567086
1     Afghanistan  1957     9240934      Asia    30.332  820.853030   7.585449
2     Afghanistan  1962    10267083      Asia    31.997  853.100710   8.758856
3     Afghanistan  1967    11537966      Asia    34.020  836.197138   9.648014
4     Afghanistan  1972    13079460      Asia    36.088  739.981106   9.678553
...           ...   ...         ...       ...       ...         ...        ...
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786   7.422612
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960   9.037851
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623   8.015111
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298   5.782658
1704   Bangladesh  1977    80428306      Asia    46.923  659.877232  53.072808

[1705 rows x 7 columns]

In [604]:
df.loc[df.duplicated()]

country  year  population continent  life_exp     gdp_cap  total_GDP
1704  Bangladesh  1977    80428306      Asia    46.923  659.877232  53.072808

In [608]:
df.drop_duplicates(keep=False)

country  year  population continent  life_exp     gdp_cap  total_GDP
0     Afghanistan  1952     8425333      Asia    28.801  779.445314   6.567086
1     Afghanistan  1957     9240934      Asia    30.332  820.853030   7.585449
2     Afghanistan  1962    10267083      Asia    31.997  853.100710   8.758856
3     Afghanistan  1967    11537966      Asia    34.020  836.197138   9.648014
4     Afghanistan  1972    13079460      Asia    36.088  739.981106   9.678553
...           ...   ...         ...       ...       ...         ...        ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306   6.508241
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786   7.422612
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960   9.037851
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623   8.015111
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298   5.782658

[1703 rows x 7 columns]

In [613]:
df.sort_values(by = ["year","total_GDP"],ascending=[False,False]).head(50)

country  year  population continent  life_exp       gdp_cap     total_GDP
1619     United States  2007   301139947  Americas    78.242  42951.653090  12934.458535
299              China  2007  1318683096      Asia    72.961   4959.114854   6539.500929
803              Japan  2007   127467972      Asia    82.603  31656.068060   4035.134797
707              India  2007  1110396331      Asia    64.698   2452.210407   2722.925439
575            Germany  2007    82400996    Europe    79.406  32170.374420   2650.870894
1607    United Kingdom  2007    60776238    Europe    79.425  33203.261280   2017.969310
539             France  2007    61083916    Europe    80.657  30470.016700   1861.227941
179             Brazil  2007   190010647  Americas    72.390   9065.800825   1722.598680
779              Italy  2007    58147733    Europe    80.546  28569.719700   1661.264433
995             Mexico  2007   108700891  Americas    76.195  11977.574960   1301.973070
251             Canada  2007    33390141  Americas    80.653  36319.235010   1212.704378
1427             Spain  2007    40448191    Europe    80.941  28821.063700   1165.759889
851        Korea, Rep.  2007    49044790      Asia    78.623  23348.139730   1145.104610
731               Iran  2007    69453570      Asia    70.964  11605.714490    806.058304
719          Indonesia  2007   223547000      Asia    70.650   3540.651564    791.502035
71           Australia  2007    20434176   Oceania    81.235  34435.367440    703.658359
1511            Taiwan  2007    23174294      Asia    78.400  28718.276840    665.525791
1091       Netherlands  2007    16570613    Europe    79.762  36797.933320    609.764312
1583            Turkey  2007    71158647    Europe    71.777   8458.276384    601.879503
1319      Saudi Arabia  2007    27601038      Asia    72.777  21654.831940    597.695839
1235            Poland  2007    38518241    Europe    75.563  15389.924680    592.792828
59           Argentina  2007    40301927  Americas    75.320  12779.379640    515.033625
1535          Thailand  2007    65068149      Asia    70.616   7458.396327    485.304044
467              Egypt  2007    80264543    Africa    71.338   5581.180998    447.970942
1175          Pakistan  2007   169270617      Asia    65.483   2605.947580    441.110355
1415      South Africa  2007    43997828    Africa    49.339   9269.657808    407.844810
119            Belgium  2007    10392226    Europe    79.441  33692.605080    350.141167
311           Colombia  2007    44227550  Americas    72.889   7006.580419    309.883886
947           Malaysia  2007    24821286      Asia    74.241  12451.655800    309.066110
1475            Sweden  2007     9031088    Europe    80.884  33859.748350    305.790367
1643         Venezuela  2007    26084662  Americas    73.747  11415.805690    297.777433
83             Austria  2007     8199783    Europe    79.829  36126.492700    296.229401
599             Greece  2007    10706290    Europe    79.483  27538.411880    294.834224
1223       Philippines  2007    91077287      Asia    71.688   3190.481016    290.580355
1487       Switzerland  2007     7554661    Europe    81.701  37506.419070    283.348281
671   Hong Kong, China  2007     6980412      Asia    82.208  39724.978670    277.296718
1139           Nigeria  2007   135031164    Africa    46.859   2013.977305    271.949700
1283           Romania  2007    22276056    Europe    72.476  10808.475610    240.770208
407     Czech Republic  2007    10228744    Europe    76.486  22833.308510    233.556067
1151            Norway  2007     4627926    Europe    80.196  49357.190170    228.421424
1247          Portugal  2007    10642836    Europe    78.098  20509.647770    218.280818
1367         Singapore  2007     4553009      Asia    79.972  47143.179640    214.643321
287              Chile  2007    16284741  Americas    78.553  13171.638850    214.496727
1211              Peru  2007    28674757  Americas    71.421   7408.905561    212.448567
107       

In [814]:
movies = pd.read_csv("movies-Copy1.csv",index_col = 0)
directors = pd.read_csv("directors-Copy1.csv",index_col = 0)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [815]:
movies

id     budget  popularity     revenue  ... director_id  year  month       day
0     43597  237000000         150  2787965087  ...        4762  2009    Dec  Thursday
1     43598  300000000         139   961000000  ...        4763  2007    May  Saturday
2     43599  245000000         107   880674609  ...        4764  2015    Oct    Monday
3     43600  250000000         112  1084939099  ...        4765  2012    Jul    Monday
5     43602  258000000         115   890871626  ...        4767  2007    May   Tuesday
...     ...        ...         ...         ...  ...         ...   ...    ...       ...
4736  48363          0           3      321952  ...        4809  1978    May    Monday
4743  48370      27000          19     3151130  ...        5369  1994    Sep   Tuesday
4748  48375          0           7           0  ...        5148  2009    Aug    Friday
4749  48376          0           3           0  ...        5535  1990    Jul    Friday
4768  48395     220000          14     2040920  ...        5097  1992    Sep    Friday

[1465 rows x 11 columns]

In [816]:
directors

director_name    id gender
0         James Cameron  4762   Male
1        Gore Verbinski  4763   Male
2            Sam Mendes  4764   Male
3     Christopher Nolan  4765   Male
4        Andrew Stanton  4766   Male
...                 ...   ...    ...
2344      Shane Carruth  7106   Male
2345   Neill Dela Llana  7107    NaN
2346        Scott Smith  7108    NaN
2347        Daniel Hsia  7109   Male
2348   Brian Herzlinger  7110   Male

[2349 rows x 3 columns]

In [817]:
df = movies.merge(right = directors,left_on="director_id",right_on="id")

In [818]:
df.drop(["director_id","id_y","gender"],axis = 1, inplace=True)

In [819]:
df

id_x     budget  popularity     revenue  ...  year  month        day      director_name
0     43597  237000000         150  2787965087  ...  2009    Dec   Thursday      James Cameron
1     43622  200000000         100  1845034188  ...  1997    Nov    Tuesday      James Cameron
2     43876  100000000         101   520000000  ...  1991    Jul     Monday      James Cameron
3     43879  115000000          38   378882411  ...  1994    Jul   Thursday      James Cameron
4     44184   70000000          24    90000098  ...  1989    Aug  Wednesday      James Cameron
...     ...        ...         ...         ...  ...   ...    ...        ...                ...
1460  46859          0          14    25288872  ...  2013    Sep  Wednesday  Nicole Holofcener
1461  47023    6500000          11    13368437  ...  2006    Sep   Thursday  Nicole Holofcener
1462  47524    3000000           5           0  ...  2010    Jan     Friday  Nicole Holofcener
1463  47962          0           0           0  ...  1996    Jul  Wednesday  Nicole Holofcener
1464  48229     250000           1     4186931  ...  2001    Aug     Friday  Nicole Holofcener

[1465 rows x 11 columns]

In [820]:
df["director_name"].nunique()

199

In [821]:
np.all(movies["director_id"].isin(directors["id"]))

True

In [822]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1465 entries, 0 to 1464
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   id_x           1465 non-null   int64  
 1   budget         1465 non-null   int64  
 2   popularity     1465 non-null   int64  
 3   revenue        1465 non-null   int64  
 4   title          1465 non-null   object 
 5   vote_average   1465 non-null   float64
 6   vote_count     1465 non-null   int64  
 7   year           1465 non-null   int64  
 8   month          1465 non-null   object 
 9   day            1465 non-null   object 
 10  director_name  1465 non-null   object 
dtypes: float64(1), int64(6), object(4)
memory usage: 137.3+ KB


In [823]:
df["budget"] = df["budget"]/1000000

In [824]:
df["revenue"] = df["revenue"]/1000000

In [825]:
df

id_x  budget  popularity      revenue  ...  year  month        day      director_name
0     43597  237.00         150  2787.965087  ...  2009    Dec   Thursday      James Cameron
1     43622  200.00         100  1845.034188  ...  1997    Nov    Tuesday      James Cameron
2     43876  100.00         101   520.000000  ...  1991    Jul     Monday      James Cameron
3     43879  115.00          38   378.882411  ...  1994    Jul   Thursday      James Cameron
4     44184   70.00          24    90.000098  ...  1989    Aug  Wednesday      James Cameron
...     ...     ...         ...          ...  ...   ...    ...        ...                ...
1460  46859    0.00          14    25.288872  ...  2013    Sep  Wednesday  Nicole Holofcener
1461  47023    6.50          11    13.368437  ...  2006    Sep   Thursday  Nicole Holofcener
1462  47524    3.00           5     0.000000  ...  2010    Jan     Friday  Nicole Holofcener
1463  47962    0.00           0     0.000000  ...  1996    Jul  Wednesday  Nicole Holofcener
1464  48229    0.25           1     4.186931  ...  2001    Aug     Friday  Nicole Holofcener

[1465 rows x 11 columns]

In [826]:
df.groupby("year")["vote_average","id_x"].aggregate({"vote_average":max,
                                                    "id_x":"unique"})

C:\Users\sunny\AppData\Local\Temp/ipykernel_32924/1080928540.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby("year")["vote_average","id_x"].aggregate({"vote_average":max,


vote_average                                               id_x
year                                                                 
1976           8.0                              [47934, 45435, 47409]
1977           7.8         [45684, 46290, 47265, 48095, 48321, 47336]
1978           7.9                [48363, 44410, 47480, 46006, 45574]
1979           8.0                       [46755, 45107, 48267, 45122]
1980           7.9  [45941, 46121, 47020, 47046, 47048, 45350, 459...
1981           7.9  [48192, 45682, 46457, 47674, 45956, 46575, 464...
1982           7.9  [45322, 46564, 46110, 44014, 47199, 45663, 449...
1983           8.0  [46603, 45447, 46124, 46609, 46980, 46771, 466...
1984           7.3  [47036, 45294, 45358, 46834, 45893, 46647, 465...
1985           8.0  [46117, 45882, 46592, 45772, 47711, 45126, 459...
1986           7.8  [46000, 46582, 47042, 47301, 46111, 45206, 447...
1987           7.6  [47438, 46045, 45924, 46807, 45686, 47158, 454...
1988           7.6  [46127, 46964, 47366, 45094, 45299, 46330, 473...
1989           7.6  [44184, 45189, 44956, 44603, 44749, 46268, 467...
1990           8.2  [45705, 44762, 45444, 46108, 43804, 45143, 453...
1991           8.1  [43876, 45146, 44169, 44966, 44498, 44778, 448...
1992           8.0  [46541, 44025, 44429, 44435, 44958, 45052, 446...
1993           8.3  [44272, 45415, 45064, 46269, 46847, 45408, 440...
1994           8.3  [43879, 47228, 45965, 47293, 44406, 46413, 458...
1995           8.1  [45111, 47051, 45134, 45588, 44292, 44489, 436...
1996           7.8  [44914, 44070, 44110, 44104, 47297, 44075, 444...
1997           7.9  [43622, 43939, 44542, 45451, 44991, 44105, 448...
1998           7.9  [46021, 46645, 43746, 44237, 44225, 44502, 440...
1999           8.3  [46113, 44561, 43667, 46407, 45086, 44231, 451...
2000           8.1  [47170, 44108, 43871, 44307, 44120, 43947, 438...
2001           8.0  [44780, 47338, 48145, 44496, 43859, 43917, 451...
2002           8.0  [44041, 44630, 43756, 45135, 43747, 44694, 439...
2003           8.1  [43796, 43800, 43926, 43999, 44180, 43783, 443...
2004           7.7  [43627, 45304, 45439, 44162, 44401, 47888, 443...
2005           7.7  [45801, 44154, 43716, 43660, 44001, 43621, 438...
2006           8.0  [43609, 44793, 44284, 43607, 45200, 45051, 436...
2007           7.9  [43598, 43602, 45783, 43878, 43620, 44150, 436...
2008           8.2  [44678, 43662, 43957, 43608, 43612, 44219, 437...
2009           7.9  [43597, 45674, 45195, 43760, 44079, 43924, 444...
2010           8.1  [43693, 43899, 43618, 43629, 44355, 47821, 436...
2011           7.7  [43775, 44144, 45272, 43614, 46681, 43991, 436...
2012           7.8  [43626, 43600, 45539, 43615, 43695, 43817, 436...
2013           7.9  [43610, 43634, 43611, 43645, 43642, 43619, 455...
2014           8.1  [43692, 43643, 44514, 43616, 43754, 46644, 439...
2015           7.7  [43599, 43867, 43641, 44784, 47719, 45049, 436...
2016           7.1  [43606, 43661, 44538, 44757, 43772, 43653, 436...

In [827]:
import numpy as np

In [828]:
# df.groupby("director_name")["budget","id_x"].aggregate({"budget":max,
#                                                        "id_x":pd.unique})

In [829]:
 df.groupby("director_name").filter(lambda x:x["budget"].max() )

TypeError: filter function returned a float, but expected a scalar bool

In [830]:
 df.groupby("director_name")["budget","id_x"].aggregate({"budget":max,"id_x":"unique"})

C:\Users\sunny\AppData\Local\Temp/ipykernel_32924/3110947703.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby("director_name")["budget","id_x"].aggregate({"budget":max,"id_x":"unique"})


budget                                               id_x
director_name                                                                         
Adam McKay                    100.0         [43882, 44151, 44236, 44503, 45301, 45443]
Adam Shankman                  80.0  [44040, 44113, 44195, 44304, 44404, 45305, 456...
Alejandro González Iñárritu   135.0         [43773, 45059, 45730, 45784, 45931, 47686]
Alex Proyas                   140.0                [43758, 43863, 44519, 44886, 45359]
Alexander Payne                30.0                [45163, 45699, 46004, 46446, 46813]
...                             ...                                                ...
Wes Craven                     40.0  [44761, 44816, 44975, 45027, 45385, 45502, 455...
Wolfgang Petersen             175.0  [43701, 43742, 43811, 43984, 44526, 45358, 46457]
Woody Allen                    30.0  [45176, 45402, 45662, 45798, 45810, 45814, 459...
Zack Snyder                   250.0  [43606, 43611, 43760, 43899, 44144, 44284, 45304]
Zhang Yimou                    94.0         [43914, 44692, 44733, 46460, 46493, 47489]

[199 rows x 2 columns]

In [831]:
g =  df.groupby("director_name")["year","title"].aggregate({"year":["min","max"],
                                                       "title":"count"}).reset_index()
g

C:\Users\sunny\AppData\Local\Temp/ipykernel_32924/668121400.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  g =  df.groupby("director_name")["year","title"].aggregate({"year":["min","max"],


director_name  year       title
                                   min   max count
0                     Adam McKay  2004  2015     6
1                  Adam Shankman  2001  2012     8
2    Alejandro González Iñárritu  2000  2015     6
3                    Alex Proyas  1994  2016     5
4                Alexander Payne  1999  2013     5
..                           ...   ...   ...   ...
194                   Wes Craven  1984  2011    10
195            Wolfgang Petersen  1981  2006     7
196                  Woody Allen  1977  2013    18
197                  Zack Snyder  2004  2016     7
198                  Zhang Yimou  2002  2014     6

[199 rows x 4 columns]

In [832]:
g["year"]["min"]

0      2004
1      2001
2      2000
3      1994
4      1999
       ... 
194    1984
195    1981
196    1977
197    2004
198    2002
Name: min, Length: 199, dtype: int64

In [833]:
df.groupby("director_name").filter(lambda x:x["budget"].max() >= 100)

id_x  budget  popularity      revenue  ...  year  month        day       director_name
0    43597   237.0         150  2787.965087  ...  2009    Dec   Thursday       James Cameron
1    43622   200.0         100  1845.034188  ...  1997    Nov    Tuesday       James Cameron
2    43876   100.0         101   520.000000  ...  1991    Jul     Monday       James Cameron
3    43879   115.0          38   378.882411  ...  1994    Jul   Thursday       James Cameron
4    44184    70.0          24    90.000098  ...  1989    Aug  Wednesday       James Cameron
..     ...     ...         ...          ...  ...   ...    ...        ...                 ...
757  44255    45.0          42    73.762516  ...  2008    Aug     Friday  Paul W.S. Anderson
758  44367    60.0          29    26.673242  ...  1997    Aug     Friday  Paul W.S. Anderson
759  44396    60.0           2   300.228084  ...  2010    Sep   Thursday  Paul W.S. Anderson
760  44992    33.0          40   102.984862  ...  2002    Mar     Friday  Paul W.S. Anderson
761  45697    18.0          16   122.195920  ...  1995    Aug     Friday  Paul W.S. Anderson

[679 rows x 11 columns]

In [834]:
def sub_avg(X):
    return X > X.mean() 
        


In [835]:
df.groupby("director_name")["budget"].transform(sub_avg)

0        True
1        True
2       False
3        True
4       False
        ...  
1460    False
1461     True
1462     True
1463    False
1464    False
Name: budget, Length: 1465, dtype: bool

In [836]:
def sub_avg(X):
    return X - X.mean()
df.groupby("director_name")["budget"].transform(sub_avg)

0       130.30
1        93.30
2        -6.70
3         8.30
4       -36.70
         ...  
1460     -1.95
1461      4.55
1462      1.05
1463     -1.95
1464     -1.70
Name: budget, Length: 1465, dtype: float64

In [837]:
def sub_avg(X):
    return X == X.max()

df[df.groupby("director_name")["budget"].transform(sub_avg)]

id_x  budget  popularity      revenue  ...  year  month       day        director_name
0     43597   237.0         150  2787.965087  ...  2009    Dec  Thursday        James Cameron
7     43598   300.0         139   961.000000  ...  2007    May  Saturday       Gore Verbinski
14    43599   245.0         107   880.674609  ...  2015    Oct    Monday           Sam Mendes
21    43600   250.0         112  1084.939099  ...  2012    Jul    Monday    Christopher Nolan
29    43602   258.0         115   890.871626  ...  2007    May   Tuesday            Sam Raimi
...     ...     ...         ...          ...  ...   ...    ...       ...                  ...
1444  46355    13.0           6    11.130889  ...  2006    Oct    Sunday       Michael Polish
1453  47263    15.0          10     0.000000  ...  2014    Dec  Thursday        Paul Schrader
1455  46574    10.0          33   163.876815  ...  2006    Oct    Friday  Darren Lynn Bousman
1456  46579    10.0          29   139.352633  ...  2007    Oct  Thursday  Darren Lynn Bousman
1461  47023     6.5          11    13.368437  ...  2006    Sep  Thursday    Nicole Holofcener

[212 rows x 11 columns]

In [838]:
df["Profit"]=df["revenue"]-df["budget"]

In [839]:
def sub_avg(X):
    return X == X.max()

df[df.groupby("director_name")["Profit"].transform(sub_avg)]["title"]

0                                           Avatar
8       Pirates of the Caribbean: Dead Man's Chest
15                                         Skyfall
21                           The Dark Knight Rises
32                                      Spider-Man
                           ...                    
1447                                     Northfork
1448                              Twin Falls Idaho
1449                                    Cat People
1455                                       Saw III
1460                                   Enough Said
Name: title, Length: 203, dtype: object

In [840]:
# df.groupby("director_name")["budget","title"].max() 

In [841]:
def sub_avg(X):
    return X == X.max()

df[df.groupby("director_name")["budget"].transform(sub_avg)].sort_values(by="director_name")

id_x  budget  popularity     revenue  ... month        day                director_name      Profit
635   43882   100.0          24  170.432927  ...   Aug     Friday                   Adam McKay   70.432927
792   44040    80.0          23  212.874442  ...   Dec  Wednesday                Adam Shankman  132.874442
465   43773   135.0         100  532.950503  ...   Dec     Friday  Alejandro González Iñárritu  397.950503
425   43758   140.0          56  150.680864  ...   Feb   Thursday                  Alex Proyas   10.680864
1341  45163    30.0          19  105.834556  ...   Dec     Friday              Alexander Payne   75.834556
...     ...     ...         ...         ...  ...   ...        ...                          ...         ...
1267  44761    40.0          24  161.834276  ...   Feb   Thursday                   Wes Craven  121.834276
325   43742   175.0          66  497.409852  ...   May   Thursday            Wolfgang Petersen  322.409852
1346  45176    30.0          43  151.119219  ...   May  Wednesday                  Woody Allen  121.119219
40    43606   250.0         155  873.260194  ...   Mar  Wednesday                  Zack Snyder  623.260194
674   43914    94.0          12   95.311434  ...   Dec   Thursday                  Zhang Yimou    1.311434

[212 rows x 12 columns]

In [848]:
def sub_avg(X):
    X["risky"] =  X["budget"] - X["revenue"].max()  >= 0 
    return X
    

df = df.groupby("director_name").apply(sub_avg)

In [849]:

# df.groupby("director_name").apply(sub_avg)

In [850]:
df[df["risky"]==True]

id_x  budget  popularity     revenue  ...        day   director_name     Profit  risky
402   43740   150.0          48  128.388320  ...   Thursday      Joe Wright -21.611680   True
1006  44316    60.0          15    0.000000  ...  Wednesday    Kenny Ortega -60.000000   True
1063  44371    72.0          15   27.642707  ...     Friday       Rod Lurie -44.357293   True
1073  44381    60.0          15    0.000000  ...   Thursday        Uwe Boll -60.000000   True
1074  45536    25.0           7    2.405420  ...   Saturday        Uwe Boll -22.594580   True
1075  45834    20.0           9   10.442808  ...     Friday        Uwe Boll  -9.557192   True
1239  44676    40.0          25   30.925690  ...     Friday     David Lynch  -9.074310   True
1405  45538    25.0           4    0.000000  ...     Friday     Atom Egoyan -25.000000   True
1408  46370    15.0          26    8.459458  ...  Wednesday     Atom Egoyan  -6.540542   True
1416  45609    23.0           6   16.123851  ...  Wednesday       Mira Nair  -6.876149   True
1444  46355    13.0           6   11.130889  ...     Sunday  Michael Polish  -1.869111   True
1450  46727    10.0           2    0.000000  ...     Friday   Paul Schrader -10.000000   True
1451  46975     7.0           7    2.062066  ...     Friday   Paul Schrader  -4.937934   True
1452  47233     5.0           6    0.000000  ...     Friday   Paul Schrader  -5.000000   True
1453  47263    15.0          10    0.000000  ...   Thursday   Paul Schrader -15.000000   True

[15 rows x 13 columns]

In [852]:
# !gdown 1XbB_dq6tH1D16Lg1OiKLXJuitQ8FdcvP

In [854]:
df = pd.read_csv("weather-Copy1.csv")
df

<IPython.core.display.Javascript object>

year  month element       day1       day2  ...      day27      day28      day29      day30      day31
0   2018      1     max  17.573016  19.796815  ...  19.700255  19.084056  18.534690  20.787275  21.117423
1   2018      1     min  22.725760  21.007865  ...  17.646139  19.844125  22.729859  19.768917  20.913443
2   2018      2     max  19.015120  19.261805  ...  20.308927  20.438899  17.005806  18.346534  20.878165
3   2018      2     min  18.653843  22.818600  ...  20.823661  18.056112  22.748292  22.470172  18.602007
4   2018      3     max  20.741115  19.704016  ...  22.591993  17.406800  19.118712  22.767154  17.119452
5   2018      3     min  17.250431  20.325829  ...  18.198453  19.469490  22.732071  19.558373  21.205858
6   2018      4     max  20.408029  21.634346  ...  20.797801  22.940309  21.036940  21.043597  18.219116
7   2018      4     min  21.849449  19.659674  ...  20.661247  20.706672  19.968800  18.643717  19.953586
8   2018      5     max  21.354089  21.806705  ...  19.362999  17.890202  18.695062  18.359134  19.559418
9   2018      5     min  18.889095  20.123320  ...  21.260536  21.358298  20.760568  19.993844  22.908548
10  2018      6     max  22.419377  20.389671  ...  21.736961  20.525993  20.003775  21.647975  17.277369
11  2018      6     min  21.121687  19.357005  ...  21.236775  22.427899  19.030243  22.954366  20.909982
12  2018      7     max  19.006195  19.512117  ...  19.359546  19.418448  22.130186  20.058017  18.371838
13  2018      7     min  19.704782  20.818029  ...  18.380388  22.157723  20.065760  21.294903  18.303314
14  2018      8     max  21.736412  20.740506  ...  19.771628  20.581845  22.614760  19.784193  21.420338
15  2018      8     min  18.896222  18.287267  ...  21.913260  18.984714  18.327634  19.071913  18.538477
16  2018     10     max  18.503314  21.919221  ...  20.695417  17.522579  18.225444  20.358178  21.530773
17  2018     10     min  22.845420  20.925599  ...  21.781845  21.758143  18.036278  17.382997  21.691537
18  2018     11     max  17.994997  18.763467  ...  22.311952  17.661902  22.275747  18.108529  20.750438
19  2018     11     min  22.275672  20.969661  ...  20.163074  20.674553  17.862405  22.946974  18.939767
20  2018     12     max  17.367511  20.085256  ...  20.528289  21.457248  19.919595  18.830226  19.648924
21  2018     12     min  18.175223  18.372862  ...  18.744409  20.488991  21.662129  20.137534  18.775539

[22 rows x 34 columns]

In [869]:
melted = pd.melt(
    frame = df,
    id_vars=["year","month","element"],
    value_vars=None,
    var_name="day",
    value_name='temp',
    col_level = None,
    ignore_index = True,)

<IPython.core.display.Javascript object>

In [870]:
melted

year  month element    day       temp
0    2018      1     max   day1  17.573016
1    2018      1     min   day1  22.725760
2    2018      2     max   day1  19.015120
3    2018      2     min   day1  18.653843
4    2018      3     max   day1  20.741115
..    ...    ...     ...    ...        ...
677  2018     10     min  day31  21.691537
678  2018     11     max  day31  20.750438
679  2018     11     min  day31  18.939767
680  2018     12     max  day31  19.648924
681  2018     12     min  day31  18.775539

[682 rows x 5 columns]

In [873]:
melted.pivot_table(
    values="temp",
    index=["year","month","day"],
    columns="element"
    )

element                 max        min
year month day                        
2018 1     day1   17.573016  22.725760
           day10  19.067288  19.931129
           day11  19.361002  22.598325
           day12  20.982134  17.715137
           day13  21.668005  17.940334
...                     ...        ...
     12    day5   21.375349  20.865535
           day6   17.992885  20.310116
           day7   19.683359  20.531823
           day8   20.477046  19.310346
           day9   20.210640  22.820992

[341 rows x 2 columns]

In [874]:
melted.pivot_table(
    values="temp",
    index=["year","month","day"],
    columns="element"
    ).reset_index()

element  year  month    day        max        min
0        2018      1   day1  17.573016  22.725760
1        2018      1  day10  19.067288  19.931129
2        2018      1  day11  19.361002  22.598325
3        2018      1  day12  20.982134  17.715137
4        2018      1  day13  21.668005  17.940334
..        ...    ...    ...        ...        ...
336      2018     12   day5  21.375349  20.865535
337      2018     12   day6  17.992885  20.310116
338      2018     12   day7  19.683359  20.531823
339      2018     12   day8  20.477046  19.310346
340      2018     12   day9  20.210640  22.820992

[341 rows x 5 columns]

In [229]:
import warnings
warnings.filterwarnings("ignore")

In [230]:
import pandas as pd
import numpy as np

In [231]:
sklearn.show_versions()


System:
    python: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\sunny\anaconda3\python.exe
   machine: Windows-10-10.0.22621-SP0

Python dependencies:
      sklearn: 1.2.0
          pip: 21.2.4
   setuptools: 58.0.4
        numpy: 1.20.3
        scipy: 1.7.1
       Cython: 0.29.24
       pandas: 1.3.4
   matplotlib: 3.4.3
       joblib: 1.2.0
threadpoolctl: 2.2.0

Built with OpenMP: True

threadpoolctl info:
       filepath: C:\Users\sunny\anaconda3\Library\bin\mkl_rt.1.dll
         prefix: mkl_rt
       user_api: blas
   internal_api: mkl
        version: 2021.4-Product
    num_threads: 6
threading_layer: intel

       filepath: C:\Users\sunny\anaconda3\Lib\site-packages\sklearn\.libs\vcomp140.dll
         prefix: vcomp
       user_api: openmp
   internal_api: openmp
        version: None
    num_threads: 12

       filepath: C:\Users\sunny\anaconda3\Library\bin\libiomp5md.dll
         prefix: libiomp
       user_api: openmp
   internal_api

In [232]:
# from sklearn.datasets import load_boston


In [233]:
# X,y = load_boston(return_X_y=True)

In [234]:
# X

In [235]:
# y

In [236]:
from sklearn.datasets import fetch_california_housing

In [237]:
print(fetch_california_housing(download_if_missing=True, return_X_y=False, as_frame=True))

{'data':        MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -1

In [238]:
data = fetch_california_housing()

In [239]:
df = pd.DataFrame(data = data.data, 
                 columns=data.feature_names)

In [240]:
data.target_names

['MedHouseVal']

In [241]:
df["MedHouseVal"] = data.target

In [242]:
df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  MedHouseVal  
0        -122.23        4.526  
1        -122.22        3.585  
2        -122.24        3.521  
3        -122.25        3.413  
4        -122.25        3.422  
...          ...          ...  
20635    -121.09        0.781  
20636    -121.21        0.771  
20637    -121.22        0.923  
20638    -121.32        0.847  
20639    -121.24        0.894  

[20640 rows x 9 columns]

In [243]:
# !pip install --upgrade scikit-learn

In [244]:
print(data.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

    :Number of Instances: 20640

    :Number of Attributes: 8 numeric, predictive attributes and the target

    :Attribute Information:
        - MedInc        median income in block group
        - HouseAge      median house age in block group
        - AveRooms      average number of rooms per household
        - AveBedrms     average number of bedrooms per household
        - Population    block group population
        - AveOccup      average number of household members
        - Latitude      block group latitude
        - Longitude     block group longitude

    :Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived

In [245]:
from category_encoders import TargetEncoder

In [246]:
te = TargetEncoder(
    verbose=0,
    cols=None,
    drop_invariant=False,
    return_df=True,
    handle_missing='value',
    handle_unknown='value',
    min_samples_leaf=1,
    smoothing=1.0,
)

In [247]:
df["Location"] = df["Latitude"].astype("str") +"_"+ df["Longitude"].astype("str")

In [248]:
df.drop(["Latitude","Longitude"],axis = 1 , inplace=True)

In [249]:
m = df.groupby("Location")["MedHouseVal"].median().reset_index()
m

Location  MedHouseVal
0      32.54_-117.04        0.675
1      32.55_-117.04        0.932
2      32.55_-117.06        1.088
3      32.55_-117.09        1.444
4      32.56_-116.97        1.533
...              ...          ...
12585   41.8_-124.17        1.094
12586    41.8_-124.3        0.858
12587  41.92_-124.16        0.750
12588  41.95_-122.64        0.535
12589  41.95_-124.14        1.224

[12590 rows x 2 columns]

In [250]:
m["Lat_encoded"] = m["MedHouseVal"] 

In [251]:
m.drop(["MedHouseVal"],axis= 1 , inplace=True)

In [252]:
m

Location  Lat_encoded
0      32.54_-117.04        0.675
1      32.55_-117.04        0.932
2      32.55_-117.06        1.088
3      32.55_-117.09        1.444
4      32.56_-116.97        1.533
...              ...          ...
12585   41.8_-124.17        1.094
12586    41.8_-124.3        0.858
12587  41.92_-124.16        0.750
12588  41.95_-122.64        0.535
12589  41.95_-124.14        1.224

[12590 rows x 2 columns]

In [253]:
df= df.merge(m,on="Location")

In [254]:
df.drop(["Location"],axis = 1 , inplace=True)

In [255]:
X = df.drop(["MedHouseVal"],axis = 1)
y = df["MedHouseVal"]

In [256]:
X

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260   
3      4.9643      37.0  7.106383   1.148936        98.0  2.085106   
4      7.2354      52.0  7.117166   0.994550       901.0  2.455041   
...       ...       ...       ...        ...         ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981   

       Lat_encoded  
0            4.526  
1            3.585  
2            3.716  
3            3.716  
4            3.716  
...            ...  
20635        0.781  
20636        0.771  
20637        0.923  
20638        0.847  
20639        0.894  

[20640 rows x 7 columns]

In [257]:
y

0        4.526
1        3.585
2        3.521
3        3.350
4        3.911
         ...  
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: MedHouseVal, Length: 20640, dtype: float64

In [258]:
from sklearn.preprocessing import StandardScaler

In [259]:
std = StandardScaler()

In [260]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [261]:
X_train , X_test,  y_train , y_test = train_test_split(X,y,
                                                      test_size=0.2,
                                                      random_state=42)

In [262]:
kfold = KFold()

In [263]:
std.fit(X_train)
X_train   = std.transform(X_train)
X_test   = std.transform(X_test)

In [264]:
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import LinearRegression

In [267]:
X_train.shape

(16512, 7)

In [274]:
# X_train.values

In [302]:
lr = LinearRegression()
lr.fit(X_train,
       y_train)

LinearRegression()

In [303]:
# !pip install sklearn

In [304]:
from sklearn.metrics import r2_score

In [305]:
folds = KFold(n_splits = 5, shuffle = True, random_state = 955)

In [306]:
cross_val_score(lr,
                X_train,
                y_train,
                scoring="r2",
                cv=folds
                )

array([0.94914781, 0.94045274, 0.9520647 , 0.9382112 , 0.9476667 ])

In [307]:
lr.score(X_test,y_test)

0.9493194660567871

In [532]:
800/1500

0.5333333333333333

In [474]:
def predict(X,w):
    return np.dot(X,w)

In [475]:
def error(X,y,w):
    y_hat = predict(X,w)
    return np.mean((y-y_hat)**2)

In [526]:
def grad(X,y,w):
    y_hat = predict(X,w)
    grad = np.dot(y_hat-y,X.T)
    return grad / len(X)

In [ ]:
def gdreg(X,y,eta=0.01):
    
    
    w = np.random.randn(X.shape[1],1)
    errors = []
    
    
    for i in range(500):
#         e = error(X,y,w)
        
#         errors.append(e)
        gradient = grad(X,y,w)
        
        w = w -   (eta * gradient)
    return w
    

In [527]:
def gdreg(X,y,eta=0.01):
    
    
    w = np.random.randn(X.shape[1],1)
    errors = []
    
    
    for i in range(500):
#         e = error(X,y,w)
        
#         errors.append(e)
        gradient = grad(X,y,w)
        
        w = w -   (eta * gradient)
    return w
    
    
    

In [538]:
from sklearn.datasets import make_regression

In [539]:
X,y = make_regression(
    n_samples=200,
    n_features=5,
    n_informative=4,
    n_targets=1,
    bias=0.0,
    effective_rank=None,
    tail_strength=0.5,
    noise=0.0,
    shuffle=True,
    coef=False,
    random_state=None,)

In [531]:
from sklearn.linear_model import SGDRegressor

In [525]:
sgd = LinearRegression()

In [513]:
sgd.fit(X,y)

LinearRegression()

In [514]:
sgd.coef_.round(2)

array([30.89, 92.46, 89.99,  0.  , 66.02])

In [515]:
sgd.intercept_

1.7763568394002505e-15

In [516]:
x = -5.5

In [517]:
x,x**2,x**3,x**4,x*5

(-5.5, 30.25, -166.375, 915.0625, -27.5)

In [535]:
X = np.array([0.0156,0.258487,0.4877898,0.987563,0.6546,0.59840,0.497,0.231,0.9873,0.98432])
X

array([0.0156   , 0.258487 , 0.4877898, 0.987563 , 0.6546   , 0.5984   ,
       0.497    , 0.231    , 0.9873   , 0.98432  ])

In [536]:
X.argmax()

3

In [537]:
X[X.argmax()]

0.987563

In [542]:
from sklearn.datasets import make_classification

In [690]:
X,y=  make_classification( 
    n_samples=1000,
    n_features=10,
    n_informative=2,
    n_redundant=5,
    n_repeated=0,
    n_classes=2,
    n_clusters_per_class=1,
    class_sep=3.0,
    hypercube=True,
    random_state=97)

In [691]:
df = pd.DataFrame(X)
df["output"] = y

In [692]:
df

0         1         2         3         4         5         6  \
0   -0.792899  0.561473  0.832673 -2.121212 -0.269128 -2.437913 -1.879642   
1    1.440262 -1.599641 -0.744350  3.087201  1.194454  2.933812  3.153730   
2    1.643245  0.751515 -0.590676  3.264486  1.600313  2.844195  3.510495   
3   -1.082790 -0.152436  0.356248 -2.118210 -1.084785 -1.809992 -2.302002   
4   -1.542322  0.399023  0.992227 -3.500517 -1.099858 -3.521355 -3.443395   
..        ...       ...       ...       ...       ...       ...       ...   
995  1.730919  0.477769 -0.651009  3.467392  1.659226  3.052014  3.707570   
996  1.248695  1.317027 -0.751171  2.782089  0.938375  2.749486  2.770152   
997 -1.418734 -0.009667  0.532733 -2.841162 -1.360763 -2.499883 -3.038588   
998 -1.368648 -0.162050  1.360692 -3.585107 -0.534923 -4.059103 -3.218525   
999  1.219700  0.227132 -0.976501  2.959539  0.693587  3.157982  2.788173   

            7         8         9  output  
0    0.095884  0.122555  0.870023       0  
1   -0.761453 -0.677699  1.092333       1  
2   -1.066461 -0.869184  1.517464       1  
3    0.727933  0.048743 -1.193503       0  
4    0.666228 -2.098801  0.482643       0  
..        ...       ...       ...     ...  
995 -1.101329 -0.018720  2.936475       1  
996 -0.579266 -0.085059 -0.877350       1  
997  0.903354  1.280805 -0.077505       0  
998  0.224082 -1.219536 -1.656691       0  
999 -0.380208 -0.560892  0.175033       1  

[1000 rows x 11 columns]

In [696]:
# sns.scatterplot(df["col1"],df["col2"],hue= df["output"])

In [697]:
X = df.drop(["output"],axis = 1)

In [698]:
y = df["output"]

In [699]:
from sklearn.model_selection import train_test_split

In [700]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2)

In [701]:
X_train

0         1         2         3         4         5         6  \
557 -1.460672  0.296932  0.955483 -3.330938 -1.027134 -3.365645 -3.266456   
782  1.650465 -0.548837 -0.712523  3.397726  1.497806  3.088709  3.566368   
928 -1.363002 -0.027147  0.363964 -2.582150 -1.443108 -2.114037 -2.869077   
267  1.054154 -0.732818 -0.828250  2.542182  0.613882  2.698786  2.404412   
217  1.341056  1.583839 -0.940058  3.120798  0.885317  3.212253  3.020271   
..        ...       ...       ...       ...       ...       ...       ...   
492 -1.416878  0.197390  0.515100 -2.820559 -1.374539 -2.463661 -3.028868   
115 -1.605153 -2.027580  0.952822 -3.563532 -1.217988 -3.509498 -3.556596   
540 -1.611995  0.770644  0.718732 -3.341278 -1.441935 -3.061108 -3.490979   
280 -1.254019 -1.833503  0.466306 -2.506739 -1.206982 -2.200741 -2.684255   
992  1.377402 -0.792943 -0.692036  2.932693  1.160535  2.767191  3.009361   

            7         8         9  
557  0.618890  0.745196  0.019850  
782 -0.979975  0.513026 -0.794425  
928  0.980898  0.942338  0.602421  
267 -0.340617  1.421229 -0.938045  
217 -0.520181  0.804533 -1.292329  
..        ...       ...       ...  
492  0.915120  0.362478 -0.596693  
115  0.754398  0.484366 -1.553801  
540  0.939688 -0.943459 -1.506390  
280  0.801974 -0.497811  2.048637  
992 -0.743378 -0.544976  1.495629  

[800 rows x 10 columns]

In [702]:
X_test

0         1         2         3         4         5         6  \
520  1.164175  0.603521 -0.790434  2.683617  0.792091  2.738696  2.613212   
519 -1.769639 -1.006119  1.347894 -4.225248 -1.069592 -4.447816 -4.021938   
558  0.976256 -1.485016 -0.916869  2.503703  0.430898  2.790855  2.277554   
932 -0.891169  1.138025  0.854368 -2.302848 -0.377350 -2.581487 -2.084956   
116 -1.703143 -1.870701  1.074046 -3.843944 -1.234422 -3.846426 -3.795103   
..        ...       ...       ...       ...       ...       ...       ...   
529 -1.955147  1.062651  0.794813 -3.975861 -1.819539 -3.563086 -4.208029   
986 -1.603661 -0.041026  0.623664 -3.232923 -1.518392 -2.867545 -3.441945   
844  1.317723  0.410519 -0.802098  2.945256  0.981613  2.919769  2.926475   
619  1.463707  0.863979 -0.739245  3.120285  1.229718  2.948063  3.199227   
50  -1.172550 -1.931400  0.768315 -2.675200 -0.823330 -2.704299 -2.622580   

            7         8         9  
520 -0.471168  0.884079 -0.090144  
519  0.604307 -0.010370 -0.017086  
558 -0.200902  0.469607 -1.319412  
932  0.170081  0.562634 -0.421498  
116  0.752242  0.135411 -2.122115  
..        ...       ...       ...  
529  1.198531 -0.381287 -0.492047  
986  1.004672  0.614942 -0.064824  
844 -0.604100 -0.352763  0.585493  
619 -0.787015  0.701396  0.108287  
50   0.495815  1.361443  0.058867  

[200 rows x 10 columns]

In [703]:
from sklearn.linear_model import LogisticRegression

In [704]:
Logitistic_reg_modol = LogisticRegression()

In [705]:
Logitistic_reg_modol.fit(X_train, y_train)

LogisticRegression()

In [706]:
Logitistic_reg_modol.score(X_train, y_train)

0.99125

In [707]:
Logitistic_reg_modol.score(X_test, y_test)

0.995

In [708]:
from sklearn.tree import DecisionTreeClassifier

In [709]:
dtc  = DecisionTreeClassifier(
    criterion='gini',
    splitter='best',
    max_depth=3,
    min_samples_split=2,
    min_samples_leaf=1,
    min_weight_fraction_leaf=0.0,
    max_features=None,
    random_state=None,
    max_leaf_nodes=None,
    min_impurity_decrease=0.0,
    class_weight=None,
    ccp_alpha=0.0,)

In [710]:
dtc.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=3)

In [711]:
dtc.score(X_train, y_train)

0.99375

In [712]:
dtc.score(X_test, y_test)

0.99

In [713]:
TP : yes ,
TN : no 
FP : no , yes
FN : yes , no 

SyntaxError: invalid syntax (Temp/ipykernel_9420/3510305992.py, line 1)

In [714]:
from sklearn.metrics import confusion_matrix

In [715]:
confusion_matrix(y_test,  dtc.predict(X_test))

array([[ 98,   1],
       [  1, 100]], dtype=int64)

In [717]:
             predicted 
            1   0 
       1 [[76, 33],
  A    0 [22, 69]]

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 3)

In [718]:
dtc.predict(X_test)

array([1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0])

In [719]:
dtc.predict_proba(X_test)[:,1]

array([0.99228792, 0.        , 0.99228792, 0.        , 0.        ,
       0.99228792, 0.99228792, 0.        , 0.99228792, 0.        ,
       0.02777778, 0.        , 0.        , 0.99228792, 0.        ,
       0.99228792, 0.        , 0.99228792, 0.875     , 0.        ,
       0.99228792, 0.        , 0.        , 0.99228792, 0.02777778,
       0.99228792, 0.        , 0.        , 0.99228792, 0.        ,
       0.99228792, 0.99228792, 0.99228792, 0.99228792, 0.99228792,
       0.        , 0.99228792, 0.99228792, 0.99228792, 0.        ,
       0.99228792, 0.99228792, 0.        , 0.99228792, 0.99228792,
       0.875     , 0.        , 0.99228792, 0.        , 0.99228792,
       0.99228792, 0.99228792, 0.99228792, 0.        , 0.        ,
       0.        , 0.99228792, 0.        , 0.99228792, 0.        ,
       0.99228792, 0.        , 0.        , 0.99228792, 0.        ,
       0.        , 0.        , 0.99228792, 0.99228792, 0.        ,
       0.        , 0.99228792, 0.        , 0.99228792, 0.99228

In [720]:
np.where(dtc.predict_proba(X_test)[:,1] > 0.65,1,0)

array([1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0])

In [721]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [722]:
recall_score(y_test,np.where(dtc.predict_proba(X_test)[:,1] > 0.55,1,0))

0.9900990099009901

In [723]:
precision_score(y_test,np.where(dtc.predict_proba(X_test)[:,1] > 0.91,1,0))

0.9897959183673469

In [724]:
f1_score(y_test,np.where(dtc.predict_proba(X_test)[:,1] > 0.59,1,0))

0.9900990099009901

In [725]:
# TP / ( TP + FP )